apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mosquitto
  name: mosquitto
spec:
  ports:
  - name: 1883-1883
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: 9001-9001
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: mosquitto
  type: ClusterIP
status:
  loadBalancer: {}
