apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:1.6
        name: eclipse-mosquitto
        resources: {}
status: {}
