apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-http
  name: api-http
spec:
  ports:
  - name: 443-3000
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
