apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: skrobul/coronadonor-api:latest
        name: coronadonor-api
        envFrom:
          - secretRef: 
              name: coronadonor-api-secrets
              optional: false
